#!/usr/bin/env bash
#Installing Nginx on Ubuntu
#Nginx is listening on port 80
#The GET request should return a page containing "Holberton School for the win!"

sudo apt update && upgrade
sudo apt install nginx -y

#Create a directory called html inside your nginx server
sudo mkdir /var/www/html
#Create a file inside that directory called index.html
sudo touch /var/www/html/index.html
#Display your message then
sudo echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx restart
